[package]
name = "jmb-gltf-renderer"
version = "0.1.0"
authors = ["John Michael Bell <johnmichaelbell@gmail.com>"]
edition = "2024"
include = ["LICENSE-APACHE", "LICENSE-MIT", "**/*.rs", "Cargo.toml"]

[package.metadata.docs.rs]
all-features = true
targets = ["x86_64-unknown-linux-gnu", "wasm32-unknown-unknown"]

[dependencies]
anyhow = "1.0"
bytemuck = { version = "1.23", features = ["derive"] }
data-url = "0.3.2"
eframe = { version = "0.36", default-features = false, features = ["default_fonts", "wgpu", "persistence", "wayland", "x11"] }
futures = "0.3"
glam = { version = "0.33", features = ["bytemuck", "serde"] }
gltf = { version = "1.4", default-features = false, features = ["KHR_lights_punctual", "extensions", "extras", "names", "utils"] }
image = "0.25.10"
ktx2 = "0.5"
log = "0.4"
puffin = { version = "0.20", features = ["web"] }
puffin_http = "0.17"
reqwest = { version = "0.13", features = ["json"] }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
wgpu = { version = "30", features = ["counters"] }

[build-dependencies]
miette = { version = "7.2", features = ["fancy"] }
wgsl_bindgen = { git = "https://github.com/Gonkalbell/wgsl-bindgen.git" }

# native:
[target.'cfg(not(target_arch = "wasm32"))'.dependencies]
env_logger = "0.11"
tokio = { version = "1.52", features = ["fs", "macros", "rt", "rt-multi-thread", "sync"] }

# web:
[target.'cfg(target_arch = "wasm32")'.dependencies]
wasm-bindgen-futures = "0.4"
web-sys = "0.3"
tokio = { version = "1.43", features = ["macros", "sync"] }

[profile.release]
opt-level = 2 # fast and small wasm

# Optimize all dependencies even in debug builds:
[profile.dev.package."*"]
opt-level = 2
