// File automatically generated by wgsl_bindgen^
//
// ^ wgsl_bindgen version 0.23.1
// Changes made to this file will not be saved.
// SourceHash: 12ee01f0b555732ebd630d65ba732c661a9395942f75ce3d1baff2a40de97981

#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash)]
pub enum ShaderEntry {
    Scene,
    Skybox,
}
impl ShaderEntry {
    pub fn create_pipeline_layout(&self, device: &wgpu::Device) -> wgpu::PipelineLayout {
        match self {
            Self::Scene => scene::create_pipeline_layout(device),
            Self::Skybox => skybox::create_pipeline_layout(device),
        }
    }
    pub fn create_shader_module_embed_source(&self, device: &wgpu::Device) -> wgpu::ShaderModule {
        match self {
            Self::Scene => scene::create_shader_module_embed_source(device),
            Self::Skybox => skybox::create_shader_module_embed_source(device),
        }
    }
}
#[allow(unused, non_snake_case, non_camel_case_types, non_upper_case_globals)]
mod _root {
    pub use super::*;
    pub trait SetBindGroup {
        fn set_bind_group(
            &mut self,
            index: u32,
            bind_group: &wgpu::BindGroup,
            offsets: &[wgpu::DynamicOffset],
        );
    }
    impl SetBindGroup for wgpu::RenderPass<'_> {
        fn set_bind_group(
            &mut self,
            index: u32,
            bind_group: &wgpu::BindGroup,
            offsets: &[wgpu::DynamicOffset],
        ) {
            self.set_bind_group(index, bind_group, offsets);
        }
    }
    impl SetBindGroup for wgpu::RenderBundleEncoder<'_> {
        fn set_bind_group(
            &mut self,
            index: u32,
            bind_group: &wgpu::BindGroup,
            offsets: &[wgpu::DynamicOffset],
        ) {
            self.set_bind_group(index, bind_group, offsets);
        }
    }
}
#[allow(unused, non_snake_case, non_camel_case_types, non_upper_case_globals)]
pub mod layout_asserts {
    use super::{_root, _root::*};
    const WGSL_BASE_TYPE_ASSERTS: () = {
        assert!(std::mem::size_of::<glam::IVec2>() == 8);
        assert!(std::mem::align_of::<glam::IVec2>() == 4);
        assert!(std::mem::size_of::<glam::IVec3>() == 12);
        assert!(std::mem::align_of::<glam::IVec3>() == 4);
        assert!(std::mem::size_of::<glam::IVec4>() == 16);
        assert!(std::mem::align_of::<glam::IVec4>() == 4);
        assert!(std::mem::size_of::<glam::UVec2>() == 8);
        assert!(std::mem::align_of::<glam::UVec2>() == 4);
        assert!(std::mem::size_of::<glam::UVec3>() == 12);
        assert!(std::mem::align_of::<glam::UVec3>() == 4);
        assert!(std::mem::size_of::<glam::UVec4>() == 16);
        assert!(std::mem::align_of::<glam::UVec4>() == 4);
        assert!(std::mem::size_of::<glam::Vec2>() == 8);
        assert!(std::mem::align_of::<glam::Vec2>() == 4);
        assert!(std::mem::size_of::<glam::Vec3>() == 12);
        assert!(std::mem::align_of::<glam::Vec3>() == 4);
        assert!(std::mem::size_of::<glam::Vec4>() == 16);
        assert!(std::mem::align_of::<glam::Vec4>() == 16);
        assert!(std::mem::size_of::<glam::Mat2>() == 16);
        assert!(std::mem::align_of::<glam::Mat2>() == 16);
        assert!(std::mem::size_of::<glam::Mat3A>() == 48);
        assert!(std::mem::align_of::<glam::Mat3A>() == 16);
        assert!(std::mem::size_of::<glam::Mat4>() == 64);
        assert!(std::mem::align_of::<glam::Mat4>() == 16);
    };
    const BGROUP_CAMERA_CAMERA_ASSERTS: () = {
        assert!(std::mem::offset_of!(bgroup_camera::Camera, world_to_local) == 0);
        assert!(std::mem::offset_of!(bgroup_camera::Camera, local_to_world) == 64);
        assert!(std::mem::offset_of!(bgroup_camera::Camera, local_to_proj) == 128);
        assert!(std::mem::offset_of!(bgroup_camera::Camera, proj_to_local) == 192);
        assert!(std::mem::offset_of!(bgroup_camera::Camera, world_to_proj) == 256);
        assert!(std::mem::offset_of!(bgroup_camera::Camera, proj_to_world) == 320);
        assert!(std::mem::align_of::<bgroup_camera::Camera>() == 16);
        assert!(std::mem::size_of::<bgroup_camera::Camera>() == 384);
    };
    const SCENE_MATERIAL_ASSERTS: () = {
        assert!(std::mem::offset_of!(scene::Material, base_color_factor) == 0);
        assert!(std::mem::offset_of!(scene::Material, alpha_cutoff) == 16);
        assert!(std::mem::align_of::<scene::Material>() == 16);
        assert!(std::mem::size_of::<scene::Material>() == 32);
    };
    const SCENE_INSTANCE_ASSERTS: () = {
        assert!(std::mem::offset_of!(scene::Instance, local_to_world) == 0);
        assert!(std::mem::offset_of!(scene::Instance, normal_local_to_world) == 64);
        assert!(std::mem::align_of::<scene::Instance>() == 16);
        assert!(std::mem::size_of::<scene::Instance>() == 128);
    };
}
#[allow(unused, non_snake_case, non_camel_case_types, non_upper_case_globals)]
pub mod bgroup_camera {
    use super::{_root, _root::*};
    #[repr(C, align(16))]
    #[derive(Debug, PartialEq, Clone, Copy, serde :: Serialize, serde :: Deserialize)]
    pub struct Camera {
        #[doc = "offset: 0, size: 64, type: `mat4x4<f32>`"]
        pub world_to_local: glam::Mat4,
        #[doc = "offset: 64, size: 64, type: `mat4x4<f32>`"]
        pub local_to_world: glam::Mat4,
        #[doc = "offset: 128, size: 64, type: `mat4x4<f32>`"]
        pub local_to_proj: glam::Mat4,
        #[doc = "offset: 192, size: 64, type: `mat4x4<f32>`"]
        pub proj_to_local: glam::Mat4,
        #[doc = "offset: 256, size: 64, type: `mat4x4<f32>`"]
        pub world_to_proj: glam::Mat4,
        #[doc = "offset: 320, size: 64, type: `mat4x4<f32>`"]
        pub proj_to_world: glam::Mat4,
    }
    impl Camera {
        pub const fn new(
            world_to_local: glam::Mat4,
            local_to_world: glam::Mat4,
            local_to_proj: glam::Mat4,
            proj_to_local: glam::Mat4,
            world_to_proj: glam::Mat4,
            proj_to_world: glam::Mat4,
        ) -> Self {
            Self {
                world_to_local,
                local_to_world,
                local_to_proj,
                proj_to_local,
                world_to_proj,
                proj_to_world,
            }
        }
    }
    #[derive(Debug)]
    pub struct WgpuBindGroup0EntriesParams<'a> {
        pub res_camera: wgpu::BufferBinding<'a>,
    }
    #[derive(Clone, Debug)]
    pub struct WgpuBindGroup0Entries<'a> {
        pub res_camera: wgpu::BindGroupEntry<'a>,
    }
    impl<'a> WgpuBindGroup0Entries<'a> {
        pub fn new(params: WgpuBindGroup0EntriesParams<'a>) -> Self {
            Self {
                res_camera: wgpu::BindGroupEntry {
                    binding: 0,
                    resource: wgpu::BindingResource::Buffer(params.res_camera),
                },
            }
        }
        pub fn into_array(self) -> [wgpu::BindGroupEntry<'a>; 1] {
            [self.res_camera]
        }
        pub fn collect<B: FromIterator<wgpu::BindGroupEntry<'a>>>(self) -> B {
            self.into_array().into_iter().collect()
        }
    }
    #[derive(Clone, Debug, Eq, Hash, Ord, PartialOrd, PartialEq)]
    pub struct WgpuBindGroup0(wgpu::BindGroup);
    impl WgpuBindGroup0 {
        pub const LAYOUT_DESCRIPTOR: wgpu::BindGroupLayoutDescriptor<'static> =
            wgpu::BindGroupLayoutDescriptor {
                label: Some("BgroupCamera::BindGroup0::LayoutDescriptor"),
                entries: &[
                    #[doc = " @binding(0): \"_root::bgroup_camera::res_camera\""]
                    wgpu::BindGroupLayoutEntry {
                        binding: 0,
                        visibility: wgpu::ShaderStages::VERTEX_FRAGMENT,
                        ty: wgpu::BindingType::Buffer {
                            ty: wgpu::BufferBindingType::Uniform,
                            has_dynamic_offset: false,
                            min_binding_size: std::num::NonZeroU64::new(std::mem::size_of::<
                                _root::bgroup_camera::Camera,
                            >(
                            )
                                as _),
                        },
                        count: None,
                    },
                ],
            };
        pub fn get_bind_group_layout(device: &wgpu::Device) -> wgpu::BindGroupLayout {
            device.create_bind_group_layout(&Self::LAYOUT_DESCRIPTOR)
        }
        pub fn from_bindings(device: &wgpu::Device, bindings: WgpuBindGroup0Entries) -> Self {
            let bind_group_layout = Self::get_bind_group_layout(device);
            let entries = bindings.into_array();
            let bind_group = device.create_bind_group(&wgpu::BindGroupDescriptor {
                label: Some("BgroupCamera::BindGroup0"),
                layout: &bind_group_layout,
                entries: &entries,
            });
            Self(bind_group)
        }
        pub fn set(&self, pass: &mut impl SetBindGroup) {
            pass.set_bind_group(0, &self.0, &[]);
        }
        pub fn inner(&self) -> &wgpu::BindGroup {
            &self.0
        }
        pub unsafe fn from_raw(bind_group: wgpu::BindGroup) -> Self {
            Self(bind_group)
        }
    }
}
#[allow(unused, non_snake_case, non_camel_case_types, non_upper_case_globals)]
pub mod bytemuck_impls {
    use super::{_root, _root::*};
    unsafe impl bytemuck::Zeroable for bgroup_camera::Camera {}
    unsafe impl bytemuck::Pod for bgroup_camera::Camera {}
    unsafe impl bytemuck::Zeroable for scene::Material {}
    unsafe impl bytemuck::Pod for scene::Material {}
    unsafe impl bytemuck::Zeroable for scene::Instance {}
    unsafe impl bytemuck::Pod for scene::Instance {}
    unsafe impl bytemuck::Zeroable for scene::VertexInput {}
    unsafe impl bytemuck::Pod for scene::VertexInput {}
}
#[allow(unused, non_snake_case, non_camel_case_types, non_upper_case_globals)]
pub mod scene {
    use super::{_root, _root::*};
    #[repr(C, align(16))]
    #[derive(Debug, PartialEq, Clone, Copy, serde :: Serialize, serde :: Deserialize)]
    pub struct Material {
        #[doc = "offset: 0, size: 16, type: `vec4<f32>`"]
        pub base_color_factor: glam::Vec4,
        #[doc = "offset: 16, size: 4, type: `f32`"]
        pub alpha_cutoff: f32,
        pub _pad_alpha_cutoff: [u8; 16 - ::core::mem::size_of::<f32>()],
    }
    impl Material {
        pub const fn new(base_color_factor: glam::Vec4, alpha_cutoff: f32) -> Self {
            Self {
                base_color_factor,
                alpha_cutoff,
                _pad_alpha_cutoff: [0; 16 - ::core::mem::size_of::<f32>()],
            }
        }
    }
    #[repr(C)]
    #[derive(Debug, PartialEq, Clone, Copy)]
    pub struct MaterialInit {
        pub base_color_factor: glam::Vec4,
        pub alpha_cutoff: f32,
    }
    impl MaterialInit {
        pub fn build(&self) -> Material {
            Material {
                base_color_factor: self.base_color_factor,
                alpha_cutoff: self.alpha_cutoff,
                _pad_alpha_cutoff: [0; 16 - ::core::mem::size_of::<f32>()],
            }
        }
    }
    impl From<MaterialInit> for Material {
        fn from(data: MaterialInit) -> Self {
            data.build()
        }
    }
    #[repr(C, align(16))]
    #[derive(Debug, PartialEq, Clone, Copy, serde :: Serialize, serde :: Deserialize)]
    pub struct Instance {
        #[doc = "offset: 0, size: 64, type: `mat4x4<f32>`"]
        pub local_to_world: glam::Mat4,
        #[doc = "offset: 64, size: 64, type: `mat4x4<f32>`"]
        pub normal_local_to_world: glam::Mat4,
    }
    impl Instance {
        pub const fn new(local_to_world: glam::Mat4, normal_local_to_world: glam::Mat4) -> Self {
            Self {
                local_to_world,
                normal_local_to_world,
            }
        }
    }
    #[repr(C)]
    #[derive(Debug, PartialEq, Clone, Copy, serde :: Serialize, serde :: Deserialize)]
    pub struct VertexInput {
        pub position: glam::Vec3,
        pub normal: glam::Vec3,
        pub tangent: glam::Vec4,
        pub texcoord_0: glam::Vec2,
        pub texcoord_1: glam::Vec2,
        pub color_0: glam::Vec4,
        pub color_1: glam::Vec4,
    }
    impl VertexInput {
        pub const fn new(
            position: glam::Vec3,
            normal: glam::Vec3,
            tangent: glam::Vec4,
            texcoord_0: glam::Vec2,
            texcoord_1: glam::Vec2,
            color_0: glam::Vec4,
            color_1: glam::Vec4,
        ) -> Self {
            Self {
                position,
                normal,
                tangent,
                texcoord_0,
                texcoord_1,
                color_0,
                color_1,
            }
        }
    }
    impl VertexInput {
        pub const VERTEX_ATTRIBUTES: [wgpu::VertexAttribute; 7] = [
            wgpu::VertexAttribute {
                format: wgpu::VertexFormat::Float32x3,
                offset: std::mem::offset_of!(Self, position) as u64,
                shader_location: 0,
            },
            wgpu::VertexAttribute {
                format: wgpu::VertexFormat::Float32x3,
                offset: std::mem::offset_of!(Self, normal) as u64,
                shader_location: 1,
            },
            wgpu::VertexAttribute {
                format: wgpu::VertexFormat::Float32x4,
                offset: std::mem::offset_of!(Self, tangent) as u64,
                shader_location: 2,
            },
            wgpu::VertexAttribute {
                format: wgpu::VertexFormat::Float32x2,
                offset: std::mem::offset_of!(Self, texcoord_0) as u64,
                shader_location: 3,
            },
            wgpu::VertexAttribute {
                format: wgpu::VertexFormat::Float32x2,
                offset: std::mem::offset_of!(Self, texcoord_1) as u64,
                shader_location: 4,
            },
            wgpu::VertexAttribute {
                format: wgpu::VertexFormat::Float32x4,
                offset: std::mem::offset_of!(Self, color_0) as u64,
                shader_location: 5,
            },
            wgpu::VertexAttribute {
                format: wgpu::VertexFormat::Float32x4,
                offset: std::mem::offset_of!(Self, color_1) as u64,
                shader_location: 6,
            },
        ];
        pub const fn vertex_buffer_layout(
            step_mode: wgpu::VertexStepMode,
        ) -> wgpu::VertexBufferLayout<'static> {
            wgpu::VertexBufferLayout {
                array_stride: std::mem::size_of::<Self>() as u64,
                step_mode,
                attributes: &Self::VERTEX_ATTRIBUTES,
            }
        }
    }
    pub const ENTRY_VS_SCENE: &str = "vs_scene";
    pub const ENTRY_FS_SCENE: &str = "fs_scene";
    #[derive(Debug)]
    pub struct VertexEntry<const N: usize> {
        pub entry_point: &'static str,
        pub buffers: [Option<wgpu::VertexBufferLayout<'static>>; N],
        pub constants: Vec<(&'static str, f64)>,
    }
    pub fn vertex_state<'a, const N: usize>(
        module: &'a wgpu::ShaderModule,
        entry: &'a VertexEntry<N>,
    ) -> wgpu::VertexState<'a> {
        wgpu::VertexState {
            module,
            entry_point: Some(entry.entry_point),
            buffers: &entry.buffers,
            compilation_options: wgpu::PipelineCompilationOptions {
                constants: &entry.constants,
                ..Default::default()
            },
        }
    }
    pub fn vs_scene_entry(vertex_input: wgpu::VertexStepMode) -> VertexEntry<1> {
        VertexEntry {
            entry_point: ENTRY_VS_SCENE,
            buffers: [Some(VertexInput::vertex_buffer_layout(vertex_input))],
            constants: Default::default(),
        }
    }
    #[derive(Debug)]
    pub struct FragmentEntry<const N: usize> {
        pub entry_point: &'static str,
        pub targets: [Option<wgpu::ColorTargetState>; N],
        pub constants: Vec<(&'static str, f64)>,
    }
    pub fn fragment_state<'a, const N: usize>(
        module: &'a wgpu::ShaderModule,
        entry: &'a FragmentEntry<N>,
    ) -> wgpu::FragmentState<'a> {
        wgpu::FragmentState {
            module,
            entry_point: Some(entry.entry_point),
            targets: &entry.targets,
            compilation_options: wgpu::PipelineCompilationOptions {
                constants: &entry.constants,
                ..Default::default()
            },
        }
    }
    pub fn fs_scene_entry(targets: [Option<wgpu::ColorTargetState>; 1]) -> FragmentEntry<1> {
        FragmentEntry {
            entry_point: ENTRY_FS_SCENE,
            targets,
            constants: Default::default(),
        }
    }
    #[derive(Debug)]
    pub struct WgpuBindGroup1EntriesParams<'a> {
        pub material_data: wgpu::BufferBinding<'a>,
        pub base_color_texture: &'a wgpu::TextureView,
        pub base_color_sampler: &'a wgpu::Sampler,
    }
    #[derive(Clone, Debug)]
    pub struct WgpuBindGroup1Entries<'a> {
        pub material_data: wgpu::BindGroupEntry<'a>,
        pub base_color_texture: wgpu::BindGroupEntry<'a>,
        pub base_color_sampler: wgpu::BindGroupEntry<'a>,
    }
    impl<'a> WgpuBindGroup1Entries<'a> {
        pub fn new(params: WgpuBindGroup1EntriesParams<'a>) -> Self {
            Self {
                material_data: wgpu::BindGroupEntry {
                    binding: 0,
                    resource: wgpu::BindingResource::Buffer(params.material_data),
                },
                base_color_texture: wgpu::BindGroupEntry {
                    binding: 2,
                    resource: wgpu::BindingResource::TextureView(params.base_color_texture),
                },
                base_color_sampler: wgpu::BindGroupEntry {
                    binding: 1,
                    resource: wgpu::BindingResource::Sampler(params.base_color_sampler),
                },
            }
        }
        pub fn into_array(self) -> [wgpu::BindGroupEntry<'a>; 3] {
            [
                self.material_data,
                self.base_color_texture,
                self.base_color_sampler,
            ]
        }
        pub fn collect<B: FromIterator<wgpu::BindGroupEntry<'a>>>(self) -> B {
            self.into_array().into_iter().collect()
        }
    }
    #[derive(Clone, Debug, Eq, Hash, Ord, PartialOrd, PartialEq)]
    pub struct WgpuBindGroup1(wgpu::BindGroup);
    impl WgpuBindGroup1 {
        pub const LAYOUT_DESCRIPTOR: wgpu::BindGroupLayoutDescriptor<'static> =
            wgpu::BindGroupLayoutDescriptor {
                label: Some("Scene::BindGroup1::LayoutDescriptor"),
                entries: &[
                    #[doc = " @binding(0): \"material_data\""]
                    wgpu::BindGroupLayoutEntry {
                        binding: 0,
                        visibility: wgpu::ShaderStages::VERTEX_FRAGMENT,
                        ty: wgpu::BindingType::Buffer {
                            ty: wgpu::BufferBindingType::Uniform,
                            has_dynamic_offset: false,
                            min_binding_size: std::num::NonZeroU64::new(std::mem::size_of::<
                                _root::scene::Material,
                            >(
                            )
                                as _),
                        },
                        count: None,
                    },
                    #[doc = " @binding(2): \"base_color_texture\""]
                    wgpu::BindGroupLayoutEntry {
                        binding: 2,
                        visibility: wgpu::ShaderStages::VERTEX_FRAGMENT,
                        ty: wgpu::BindingType::Texture {
                            sample_type: wgpu::TextureSampleType::Float { filterable: true },
                            view_dimension: wgpu::TextureViewDimension::D2,
                            multisampled: false,
                        },
                        count: None,
                    },
                    #[doc = " @binding(1): \"base_color_sampler\""]
                    wgpu::BindGroupLayoutEntry {
                        binding: 1,
                        visibility: wgpu::ShaderStages::VERTEX_FRAGMENT,
                        ty: wgpu::BindingType::Sampler(wgpu::SamplerBindingType::Filtering),
                        count: None,
                    },
                ],
            };
        pub fn get_bind_group_layout(device: &wgpu::Device) -> wgpu::BindGroupLayout {
            device.create_bind_group_layout(&Self::LAYOUT_DESCRIPTOR)
        }
        pub fn from_bindings(device: &wgpu::Device, bindings: WgpuBindGroup1Entries) -> Self {
            let bind_group_layout = Self::get_bind_group_layout(device);
            let entries = bindings.into_array();
            let bind_group = device.create_bind_group(&wgpu::BindGroupDescriptor {
                label: Some("Scene::BindGroup1"),
                layout: &bind_group_layout,
                entries: &entries,
            });
            Self(bind_group)
        }
        pub fn set(&self, pass: &mut impl SetBindGroup) {
            pass.set_bind_group(1, &self.0, &[]);
        }
        pub fn inner(&self) -> &wgpu::BindGroup {
            &self.0
        }
        pub unsafe fn from_raw(bind_group: wgpu::BindGroup) -> Self {
            Self(bind_group)
        }
    }
    #[derive(Debug)]
    pub struct WgpuBindGroup2EntriesParams<'a> {
        pub res_instances: wgpu::BufferBinding<'a>,
    }
    #[derive(Clone, Debug)]
    pub struct WgpuBindGroup2Entries<'a> {
        pub res_instances: wgpu::BindGroupEntry<'a>,
    }
    impl<'a> WgpuBindGroup2Entries<'a> {
        pub fn new(params: WgpuBindGroup2EntriesParams<'a>) -> Self {
            Self {
                res_instances: wgpu::BindGroupEntry {
                    binding: 0,
                    resource: wgpu::BindingResource::Buffer(params.res_instances),
                },
            }
        }
        pub fn into_array(self) -> [wgpu::BindGroupEntry<'a>; 1] {
            [self.res_instances]
        }
        pub fn collect<B: FromIterator<wgpu::BindGroupEntry<'a>>>(self) -> B {
            self.into_array().into_iter().collect()
        }
    }
    #[derive(Clone, Debug, Eq, Hash, Ord, PartialOrd, PartialEq)]
    pub struct WgpuBindGroup2(wgpu::BindGroup);
    impl WgpuBindGroup2 {
        pub const LAYOUT_DESCRIPTOR: wgpu::BindGroupLayoutDescriptor<'static> =
            wgpu::BindGroupLayoutDescriptor {
                label: Some("Scene::BindGroup2::LayoutDescriptor"),
                entries: &[
                    #[doc = " @binding(0): \"res_instances\""]
                    wgpu::BindGroupLayoutEntry {
                        binding: 0,
                        visibility: wgpu::ShaderStages::VERTEX_FRAGMENT,
                        ty: wgpu::BindingType::Buffer {
                            ty: wgpu::BufferBindingType::Storage { read_only: true },
                            has_dynamic_offset: false,
                            min_binding_size: None,
                        },
                        count: None,
                    },
                ],
            };
        pub fn get_bind_group_layout(device: &wgpu::Device) -> wgpu::BindGroupLayout {
            device.create_bind_group_layout(&Self::LAYOUT_DESCRIPTOR)
        }
        pub fn from_bindings(device: &wgpu::Device, bindings: WgpuBindGroup2Entries) -> Self {
            let bind_group_layout = Self::get_bind_group_layout(device);
            let entries = bindings.into_array();
            let bind_group = device.create_bind_group(&wgpu::BindGroupDescriptor {
                label: Some("Scene::BindGroup2"),
                layout: &bind_group_layout,
                entries: &entries,
            });
            Self(bind_group)
        }
        pub fn set(&self, pass: &mut impl SetBindGroup) {
            pass.set_bind_group(2, &self.0, &[]);
        }
        pub fn inner(&self) -> &wgpu::BindGroup {
            &self.0
        }
        pub unsafe fn from_raw(bind_group: wgpu::BindGroup) -> Self {
            Self(bind_group)
        }
    }
    #[doc = " Bind groups can be set individually using their set(render_pass) method, or all at once using `WgpuBindGroups::set`."]
    #[doc = " For optimal performance with many draw calls, it's recommended to organize bindings into bind groups based on update frequency:"]
    #[doc = "   - Bind group 0: Least frequent updates (e.g. per frame resources)"]
    #[doc = "   - Bind group 1: More frequent updates"]
    #[doc = "   - Bind group 2: More frequent updates"]
    #[doc = "   - Bind group 3: Most frequent updates (e.g. per draw resources)"]
    #[derive(Debug, Copy, Clone)]
    pub struct WgpuBindGroups<'a> {
        pub bind_group0: &'a bgroup_camera::WgpuBindGroup0,
        pub bind_group1: &'a WgpuBindGroup1,
        pub bind_group2: &'a WgpuBindGroup2,
    }
    impl<'a> WgpuBindGroups<'a> {
        pub fn set(&self, pass: &mut impl SetBindGroup) {
            self.bind_group0.set(pass);
            self.bind_group1.set(pass);
            self.bind_group2.set(pass);
        }
    }
    #[derive(Debug)]
    pub struct WgpuPipelineLayout;
    impl WgpuPipelineLayout {
        pub fn bind_group_layout_entries(
            entries: [wgpu::BindGroupLayout; 3],
        ) -> [wgpu::BindGroupLayout; 3] {
            entries
        }
    }
    pub fn create_pipeline_layout(device: &wgpu::Device) -> wgpu::PipelineLayout {
        device.create_pipeline_layout(&wgpu::PipelineLayoutDescriptor {
            label: Some("Scene::PipelineLayout"),
            bind_group_layouts: &[
                Some(&bgroup_camera::WgpuBindGroup0::get_bind_group_layout(
                    device,
                )),
                Some(&WgpuBindGroup1::get_bind_group_layout(device)),
                Some(&WgpuBindGroup2::get_bind_group_layout(device)),
            ],
            immediate_size: 0u32,
        })
    }
    pub fn create_shader_module_embed_source(device: &wgpu::Device) -> wgpu::ShaderModule {
        let source = std::borrow::Cow::Borrowed(SHADER_STRING);
        device.create_shader_module(wgpu::ShaderModuleDescriptor {
            label: Some("scene.wgsl"),
            source: wgpu::ShaderSource::Wgsl(source),
        })
    }
    pub const SHADER_STRING: &str = r#"
struct CameraX_naga_oil_mod_XMJTXE33VOBPWGYLNMVZGCX {
    world_to_local: mat4x4<f32>,
    local_to_world: mat4x4<f32>,
    local_to_proj: mat4x4<f32>,
    proj_to_local: mat4x4<f32>,
    world_to_proj: mat4x4<f32>,
    proj_to_world: mat4x4<f32>,
}

struct Material {
    base_color_factor: vec4<f32>,
    alpha_cutoff: f32,
}

struct Instance {
    local_to_world: mat4x4<f32>,
    normal_local_to_world: mat4x4<f32>,
}

struct VertexInput {
    @location(0) position: vec3<f32>,
    @location(1) normal: vec3<f32>,
    @location(2) tangent: vec4<f32>,
    @location(3) texcoord_0_: vec2<f32>,
    @location(4) texcoord_1_: vec2<f32>,
    @location(5) color_0_: vec4<f32>,
    @location(6) color_1_: vec4<f32>,
}

struct VertexOutput {
    @builtin(position) position: vec4<f32>,
    @location(0) view_position: vec4<f32>,
    @location(1) normal: vec3<f32>,
    @location(2) tangent: vec3<f32>,
    @location(3) texcoord_0_: vec2<f32>,
    @location(4) texcoord_1_: vec2<f32>,
    @location(5) color_0_: vec4<f32>,
    @location(6) color_1_: vec4<f32>,
}

const LIGHT_DIR: vec3<f32> = vec3<f32>(0.25f, 0.5f, 1f);
const LIGHT_COLOR: vec3<f32> = vec3(1f);
const AMBIENT_COLOR: vec3<f32> = vec3(0.1f);

@group(0) @binding(0) 
var<uniform> res_cameraX_naga_oil_mod_XMJTXE33VOBPWGYLNMVZGCX: CameraX_naga_oil_mod_XMJTXE33VOBPWGYLNMVZGCX;
@group(1) @binding(0) 
var<uniform> material_data: Material;
@group(1) @binding(2) 
var base_color_texture: texture_2d<f32>;
@group(1) @binding(1) 
var base_color_sampler: sampler;
@group(2) @binding(0) 
var<storage> res_instances: array<Instance>;

@vertex 
fn vs_scene(@builtin(instance_index) instance_index: u32, input: VertexInput) -> VertexOutput {
    var output: VertexOutput;
    var instance: Instance;

    let _e3 = res_instances[instance_index];
    instance = _e3;
    let _e10 = res_cameraX_naga_oil_mod_XMJTXE33VOBPWGYLNMVZGCX.world_to_proj;
    let _e12 = instance.local_to_world;
    output.position = ((_e10 * _e12) * vec4<f32>(input.position, 1f));
    let _e21 = res_cameraX_naga_oil_mod_XMJTXE33VOBPWGYLNMVZGCX.world_to_local;
    let _e23 = instance.local_to_world;
    output.view_position = ((_e21 * _e23) * vec4<f32>(input.position, 1f));
    let _e32 = res_cameraX_naga_oil_mod_XMJTXE33VOBPWGYLNMVZGCX.world_to_local;
    let _e34 = instance.normal_local_to_world;
    output.normal = ((_e32 * _e34) * vec4<f32>(input.normal, 0f)).xyz;
    let _e44 = res_cameraX_naga_oil_mod_XMJTXE33VOBPWGYLNMVZGCX.world_to_local;
    let _e46 = instance.normal_local_to_world;
    output.tangent = ((_e44 * _e46) * vec4<f32>(input.tangent.xyz, 0f)).xyz;
    output.texcoord_0_ = input.texcoord_0_;
    output.texcoord_1_ = input.texcoord_1_;
    output.color_0_ = input.color_0_;
    output.color_1_ = input.color_1_;
    let _e62 = output;
    return _e62;
}

@fragment 
fn fs_scene(input_1: VertexOutput, @builtin(front_facing) front_facing: bool) -> @location(0) vec4<f32> {
    var N: vec3<f32>;

    let _e5 = textureSample(base_color_texture, base_color_sampler, input_1.texcoord_0_);
    let _e9 = material_data.base_color_factor;
    let base_color = ((input_1.color_0_ * _e5) * _e9);
    let _e14 = material_data.alpha_cutoff;
    if (base_color.w < _e14) {
        discard;
    }
    N = input_1.normal;
    let _e18 = N;
    if all((_e18 == vec3(0f))) {
        let view_position = input_1.view_position.xyz;
        let dx = dpdx(view_position);
        let dy = dpdy(view_position);
        N = cross(dy, dx);
    }
    let _e32 = N;
    N = (select(-1f, 1f, front_facing) * normalize(_e32));
    let L = vec3<f32>(0.21821788f, 0.43643576f, 0.8728715f);
    let _e39 = N;
    let NDotL = max(dot(_e39, L), 0f);
    let surface_color = ((base_color.xyz * AMBIENT_COLOR) + (base_color.xyz * NDotL));
    return vec4<f32>(surface_color, base_color.w);
}
"#;
}
#[allow(unused, non_snake_case, non_camel_case_types, non_upper_case_globals)]
pub mod skybox {
    use super::{_root, _root::*};
    pub const ENTRY_VS_SKYBOX: &str = "vs_skybox";
    pub const ENTRY_FS_SKYBOX: &str = "fs_skybox";
    #[derive(Debug)]
    pub struct VertexEntry<const N: usize> {
        pub entry_point: &'static str,
        pub buffers: [Option<wgpu::VertexBufferLayout<'static>>; N],
        pub constants: Vec<(&'static str, f64)>,
    }
    pub fn vertex_state<'a, const N: usize>(
        module: &'a wgpu::ShaderModule,
        entry: &'a VertexEntry<N>,
    ) -> wgpu::VertexState<'a> {
        wgpu::VertexState {
            module,
            entry_point: Some(entry.entry_point),
            buffers: &entry.buffers,
            compilation_options: wgpu::PipelineCompilationOptions {
                constants: &entry.constants,
                ..Default::default()
            },
        }
    }
    pub fn vs_skybox_entry() -> VertexEntry<0> {
        VertexEntry {
            entry_point: ENTRY_VS_SKYBOX,
            buffers: [],
            constants: Default::default(),
        }
    }
    #[derive(Debug)]
    pub struct FragmentEntry<const N: usize> {
        pub entry_point: &'static str,
        pub targets: [Option<wgpu::ColorTargetState>; N],
        pub constants: Vec<(&'static str, f64)>,
    }
    pub fn fragment_state<'a, const N: usize>(
        module: &'a wgpu::ShaderModule,
        entry: &'a FragmentEntry<N>,
    ) -> wgpu::FragmentState<'a> {
        wgpu::FragmentState {
            module,
            entry_point: Some(entry.entry_point),
            targets: &entry.targets,
            compilation_options: wgpu::PipelineCompilationOptions {
                constants: &entry.constants,
                ..Default::default()
            },
        }
    }
    pub fn fs_skybox_entry(targets: [Option<wgpu::ColorTargetState>; 1]) -> FragmentEntry<1> {
        FragmentEntry {
            entry_point: ENTRY_FS_SKYBOX,
            targets,
            constants: Default::default(),
        }
    }
    #[derive(Debug)]
    pub struct WgpuBindGroup1EntriesParams<'a> {
        pub res_texture: &'a wgpu::TextureView,
        pub res_sampler: &'a wgpu::Sampler,
    }
    #[derive(Clone, Debug)]
    pub struct WgpuBindGroup1Entries<'a> {
        pub res_texture: wgpu::BindGroupEntry<'a>,
        pub res_sampler: wgpu::BindGroupEntry<'a>,
    }
    impl<'a> WgpuBindGroup1Entries<'a> {
        pub fn new(params: WgpuBindGroup1EntriesParams<'a>) -> Self {
            Self {
                res_texture: wgpu::BindGroupEntry {
                    binding: 0,
                    resource: wgpu::BindingResource::TextureView(params.res_texture),
                },
                res_sampler: wgpu::BindGroupEntry {
                    binding: 1,
                    resource: wgpu::BindingResource::Sampler(params.res_sampler),
                },
            }
        }
        pub fn into_array(self) -> [wgpu::BindGroupEntry<'a>; 2] {
            [self.res_texture, self.res_sampler]
        }
        pub fn collect<B: FromIterator<wgpu::BindGroupEntry<'a>>>(self) -> B {
            self.into_array().into_iter().collect()
        }
    }
    #[derive(Clone, Debug, Eq, Hash, Ord, PartialOrd, PartialEq)]
    pub struct WgpuBindGroup1(wgpu::BindGroup);
    impl WgpuBindGroup1 {
        pub const LAYOUT_DESCRIPTOR: wgpu::BindGroupLayoutDescriptor<'static> =
            wgpu::BindGroupLayoutDescriptor {
                label: Some("Skybox::BindGroup1::LayoutDescriptor"),
                entries: &[
                    #[doc = " @binding(0): \"res_texture\""]
                    wgpu::BindGroupLayoutEntry {
                        binding: 0,
                        visibility: wgpu::ShaderStages::VERTEX_FRAGMENT,
                        ty: wgpu::BindingType::Texture {
                            sample_type: wgpu::TextureSampleType::Float { filterable: true },
                            view_dimension: wgpu::TextureViewDimension::Cube,
                            multisampled: false,
                        },
                        count: None,
                    },
                    #[doc = " @binding(1): \"res_sampler\""]
                    wgpu::BindGroupLayoutEntry {
                        binding: 1,
                        visibility: wgpu::ShaderStages::VERTEX_FRAGMENT,
                        ty: wgpu::BindingType::Sampler(wgpu::SamplerBindingType::Filtering),
                        count: None,
                    },
                ],
            };
        pub fn get_bind_group_layout(device: &wgpu::Device) -> wgpu::BindGroupLayout {
            device.create_bind_group_layout(&Self::LAYOUT_DESCRIPTOR)
        }
        pub fn from_bindings(device: &wgpu::Device, bindings: WgpuBindGroup1Entries) -> Self {
            let bind_group_layout = Self::get_bind_group_layout(device);
            let entries = bindings.into_array();
            let bind_group = device.create_bind_group(&wgpu::BindGroupDescriptor {
                label: Some("Skybox::BindGroup1"),
                layout: &bind_group_layout,
                entries: &entries,
            });
            Self(bind_group)
        }
        pub fn set(&self, pass: &mut impl SetBindGroup) {
            pass.set_bind_group(1, &self.0, &[]);
        }
        pub fn inner(&self) -> &wgpu::BindGroup {
            &self.0
        }
        pub unsafe fn from_raw(bind_group: wgpu::BindGroup) -> Self {
            Self(bind_group)
        }
    }
    #[doc = " Bind groups can be set individually using their set(render_pass) method, or all at once using `WgpuBindGroups::set`."]
    #[doc = " For optimal performance with many draw calls, it's recommended to organize bindings into bind groups based on update frequency:"]
    #[doc = "   - Bind group 0: Least frequent updates (e.g. per frame resources)"]
    #[doc = "   - Bind group 1: More frequent updates"]
    #[doc = "   - Bind group 2: More frequent updates"]
    #[doc = "   - Bind group 3: Most frequent updates (e.g. per draw resources)"]
    #[derive(Debug, Copy, Clone)]
    pub struct WgpuBindGroups<'a> {
        pub bind_group0: &'a bgroup_camera::WgpuBindGroup0,
        pub bind_group1: &'a WgpuBindGroup1,
    }
    impl<'a> WgpuBindGroups<'a> {
        pub fn set(&self, pass: &mut impl SetBindGroup) {
            self.bind_group0.set(pass);
            self.bind_group1.set(pass);
        }
    }
    #[derive(Debug)]
    pub struct WgpuPipelineLayout;
    impl WgpuPipelineLayout {
        pub fn bind_group_layout_entries(
            entries: [wgpu::BindGroupLayout; 2],
        ) -> [wgpu::BindGroupLayout; 2] {
            entries
        }
    }
    pub fn create_pipeline_layout(device: &wgpu::Device) -> wgpu::PipelineLayout {
        device.create_pipeline_layout(&wgpu::PipelineLayoutDescriptor {
            label: Some("Skybox::PipelineLayout"),
            bind_group_layouts: &[
                Some(&bgroup_camera::WgpuBindGroup0::get_bind_group_layout(
                    device,
                )),
                Some(&WgpuBindGroup1::get_bind_group_layout(device)),
            ],
            immediate_size: 0u32,
        })
    }
    pub fn create_shader_module_embed_source(device: &wgpu::Device) -> wgpu::ShaderModule {
        let source = std::borrow::Cow::Borrowed(SHADER_STRING);
        device.create_shader_module(wgpu::ShaderModuleDescriptor {
            label: Some("skybox.wgsl"),
            source: wgpu::ShaderSource::Wgsl(source),
        })
    }
    pub const SHADER_STRING: &str = r#"
struct CameraX_naga_oil_mod_XMJTXE33VOBPWGYLNMVZGCX {
    world_to_local: mat4x4<f32>,
    local_to_world: mat4x4<f32>,
    local_to_proj: mat4x4<f32>,
    proj_to_local: mat4x4<f32>,
    world_to_proj: mat4x4<f32>,
    proj_to_world: mat4x4<f32>,
}

struct SkyboxInterp {
    @builtin(position) position: vec4<f32>,
    @location(0) tex_coord: vec3<f32>,
}

@group(0) @binding(0) 
var<uniform> res_cameraX_naga_oil_mod_XMJTXE33VOBPWGYLNMVZGCX: CameraX_naga_oil_mod_XMJTXE33VOBPWGYLNMVZGCX;
@group(1) @binding(0) 
var res_texture: texture_cube<f32>;
@group(1) @binding(1) 
var res_sampler: sampler;

@vertex 
fn vs_skybox(@builtin(vertex_index) vertex_index: u32) -> SkyboxInterp {
    var result: SkyboxInterp;

    let tmp1_ = (i32(vertex_index) / 2i);
    let tmp2_ = (i32(vertex_index) & 1i);
    let pos = vec4<f32>(((f32(tmp1_) * 4f) - 1f), ((f32(tmp2_) * 4f) - 1f), 1f, 1f);
    result.position = pos;
    let _e24 = res_cameraX_naga_oil_mod_XMJTXE33VOBPWGYLNMVZGCX.proj_to_local;
    let dir = vec4<f32>((_e24 * pos).xyz, 0f);
    let _e32 = res_cameraX_naga_oil_mod_XMJTXE33VOBPWGYLNMVZGCX.local_to_world;
    result.tex_coord = (_e32 * dir).xyz;
    let _e35 = result;
    return _e35;
}

@fragment 
fn fs_skybox(vertex: SkyboxInterp) -> @location(0) vec4<f32> {
    let _e4 = textureSample(res_texture, res_sampler, vertex.tex_coord);
    return _e4;
}
"#;
}
